version: "3.3"
services:
  pathways:
    build:
      dockerfile: Dockerfile-pathways
    container_name: pathways-container
    environment:
      - IS_LOCAL_ENV=0
    volumes:
      - ~/code/clinical-pathways:/app
    ports:
      - 5000:5000
    restart: unless-stopped
    working_dir: /app
    command: python app.py --server --host=0.0.0.0
volumes:
  app:
    external: true


#    tiangolo/uvicorn-gunicorn-fastapi:
#
#
#version: '3'
#
#services:
#  django:
#    image: python:3.7-alpine
#    volumes:
#     - pip37:/usr/local/lib/python3.7/site-packages
#     - .:/project
#    ports:
#      - 8000:8000
#    working_dir: /project
#    command: python manage.py runserver
#    depends_on:
#      - requirements
#
#  requirements:
#    image: python:3.7-alpine
#    volumes:
#      - pip37:/usr/local/lib/python3.7/site-packages
#      - .:/project
#    working_dir: /project
#    command: pip install -r requirements.txt
#
#volumes:
#  pip37:
#    external: true